FROM node:alpine AS builder


ARG NEXT_PUBLIC_URL
ARG NEXT_PUBLIC_AUTO_VERIFICATION
ARG NEXT_PUBLIC_WEB_SOCKET
ARG NEXT_PUBLIC_DOMAIN
ARG NEXT_PUBLIC_API_KEY_YANDEX

ENV NEXT_PUBLIC_URL=$NEXT_PUBLIC_URL
ENV NEXT_PUBLIC_AUTO_VERIFICATION=$NEXT_PUBLIC_AUTO_VERIFICATION
ENV NEXT_PUBLIC_WEB_SOCKET=$NEXT_PUBLIC_WEB_SOCKET
ENV NEXT_PUBLIC_DOMAIN=$NEXT_PUBLIC_DOMAIN
ENV NEXT_PUBLIC_API_KEY_YANDEX=$NEXT_PUBLIC_API_KEY_YANDEX

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm ci

FROM node:alpine

ARG NEXT_PUBLIC_URL
ARG NEXT_PUBLIC_AUTO_VERIFICATION
ARG NEXT_PUBLIC_WEB_SOCKET
ARG NEXT_PUBLIC_DOMAIN
ARG NEXT_PUBLIC_API_KEY_YANDEX

ENV NEXT_PUBLIC_URL=$NEXT_PUBLIC_URL
ENV NEXT_PUBLIC_AUTO_VERIFICATION=$NEXT_PUBLIC_AUTO_VERIFICATION
ENV NEXT_PUBLIC_WEB_SOCKET=$NEXT_PUBLIC_WEB_SOCKET
ENV NEXT_PUBLIC_DOMAIN=$NEXT_PUBLIC_DOMAIN
ENV NEXT_PUBLIC_API_KEY_YANDEX=$NEXT_PUBLIC_API_KEY_YANDEX

WORKDIR /app

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules

COPY . .

RUN npm run build
