/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
    "./src/utils/icons/**/*.{js,ts,jsx,tsx}",
    "./src/context/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      current: "currentColor",
      "text-primary": "var(--text-primary)",
      "text-disabled": "var(--text-disabled)",
      "text-secondary": "var(--text-secondary)",
      "element-accent-1": "var(--element-accent-1)",
      "element-accent-2": "var(--element-accent-2)",
      "grey-stroke-light": "var(--grey-stroke-light)",
      "BG-second": "var(--BG-second)",
      "BG-first": "var(--BG-first)",
      "BG-icons": "var(--BG-icons)",
      "BG-filter": "var(--BG-filter)",
      "text-button": "var(--text-button)",
      "text-error": "var(--text-error)",
      "text-attention": "var(--text-attention)",
      "more-green": "var(--more-field)",
      "element-white": "var(--element-white)",
      "text-tab": "var(--text-tab)",
      "more-field": "var(--more-field)",
      "btn-second-default": "var(--btn-second-default)",
      "btn-second-hover": "var(--btn-second-hover)",
      "btn-main-default": "var(--btn-main-default)",
      "btn-main-hover": "var(--btn-main-hover)",
      "opacity-white-hard": "var(--opacity-white-hard)",
      "supporting-white": "var(--supporting-white)",
      "link-color": "var(--link-color)",
      translucent: "var(--translucent)",
      "translucent-0.8": "rgba(16, 24, 40, 0.80)",
      transparent: "transparent",
      "grey-field": "var(--grey-field)",
      "element-grey-light": "var(--element-grey-light)",
      "element-grey": "var(--element-grey)",
      "grey-separator": "var(--grey-separator)",
      "element-error": "var(--element-error)",
      "text-accent": "var(--text-accent)",
      "more-red": "var(--more-red)",
      "grey-stroke": "var(--grey-stroke)",
      "BG-chat": "var(--BG-chat)",
      "BG-time": "var(--BG-time)",
      "BG-linear-purple": "linear-gradient(95deg, #B3D2FF -26.18%, #D8BAFF 130.54%)",
      "BG-filter-red": "var(--filter-red)",
      "more-blue-gradient": "var(--more-blue-gradient)",

      //bg-card

      "card-red": "var(--card-red)",
      "card-border-red": "var(--card-border-red)",
      "card-blue": "var(--card-blue)",
      "card-border-blue": "var(--card-border-blue)",
      "card-yellow": "var(--card-yellow)",
      "card-border-yellow": "var(--card-border-yellow)",
    },
    extend: {
      spacing: {
        "2rem": "2rem",
        "standard-header-modal": "var(--height-standard-header-modal)",
        "full-minus-standard-header-modal": "calc(100% - var(--height-standard-header-modal))",
      },
      borderRadius: {
        2: "2rem",
        ".625": "0.625rem",
      },
      boxShadow: {
        "social-link": "0px 11px 20px 0px rgba(100, 104, 115, 0.1)",
        "menu-absolute": "0px 10px 16px 0px rgba(31, 31, 41, 0.1)",
        "box-down": "0px 4px 10px 0px rgba(0, 0, 0, 0.24)",
      },
    },
  },
  plugins: [],
}
