/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}", "./src/app/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    colors: {
      current: "currentColor",
      "text-primary": "var(--text-primary)",
      "text-disabled": "var(--text-disabled)",
      "text-secondary": "var(--text-secondary)",
      "element-accent-1": "var(--element-accent-1)",
      "element-accent-2": "var(--element-accent-2)",
      "grey-stroke-light": "var(--grey-stroke-light)",
      "BG-second": "var(--BG-second)",
      "BG-first": "var(--BG-first)",
      "BG-icons": "var(--BG-icons)",
      "text-button": "var(--text-button)",
      "text-error": "var(--text-error)",
      "text-attention": "var(--text-attention)",
      "more-green": "var(--more-field)",
      "element-white": "var(--element-white)",
      "text-tab": "var(--text-tab)",
      "more-field": "var(--more-field)",
      "btn-second-default": "var(--btn-second-default)",
      "btn-second-hover": "var(--btn-second-hover)",
      "btn-main-default": "var(--btn-main-default)",
      "btn-main-hover": "var(--btn-main-hover)",
      "opacity-white-hard": "var(--opacity-white-hard)",
      "supporting-white": "var(--supporting-white)",
      translucent: "rgba(5, 1, 13, 0.50)",
      "translucent-0.8": "rgba(16, 24, 40, 0.80)",
      transparent: "transparent",
      "grey-field": "var(--grey-field)",
      "element-grey-light": "var(--element-grey-light)",
      "element-grey": "var(--element-grey)",
      "grey-separator": "var(--grey-separator)",
      "element-error": "var(--element-error)",
      "text-accent": "var(--text-accent)",
      "more-red": "var(--more-red)",
      "grey-stroke": "var(--grey-stroke)",
    },
    extend: {
      spacing: {
        0.125: "0.125rem",
        0.875: "0.875rem",
        0.625: "0.625rem",
        0.375: "0.375rem",
        "2rem": "2rem",
        "1px": "1px",
      },
      boxShadow: {
        "social-link": "0px 11px 20px 0px rgba(100, 104, 115, 0.1)",
        "menu-absolute": "0px 10px 16px 0px rgba(31, 31, 41, 0.1)",
      },
    },
  },
  plugins: [],
}
