import {
  FlagAM,
  FlagAZ,
  FlagBY,
  FlagCA,
  FlagDE,
  FlagEE,
  FlagES,
  FlagFR,
  FlagGE,
  FlagIL,
  FlagIN,
  FlagKG,
  FlagKZ,
  FlagLT,
  FlagLV,
  FlagRS,
  FlagRU,
  FlagTH,
  FlagTR,
  FlagUS,
  FlagUZ,
} from "./icons-flags"

export enum EnumCountry {
  ru = "ru",
  by = "by",
  kz = "kz",
  az = "az",
  am = "am",
  de = "de",
  ge = "ge",
  il = "il",
  in = "in",
  es = "es",
  ca = "ca",
  kg = "kg",
  lv = "lv",
  lt = "lt",
  rs = "rs",
  us = "us",
  th = "th",
  tr = "tr",
  uz = "uz",
  fr = "fr",
  ee = "ee",
}

export interface IFlag {
  img: () => JSX.Element
  short: EnumCountry
  name: string
  code: string
  mask: string
  placeholder: string
  selectionStart: number
}

export const FLAGS: IFlag[] = [
  {
    img: FlagAZ,
    short: EnumCountry.az,
    name: "Азербайджан",
    code: "+994",
    mask: "+___ (___) ___-__-__",
    placeholder: "+994 (999) 000-00-00",
    selectionStart: 3,
  },
  {
    img: FlagAM,
    short: EnumCountry.am,
    name: "Армения",
    code: "+374",
    mask: "+___ (__) ___-___",
    placeholder: "+374 (99) 000-000",
    selectionStart: 3,
  },
  {
    img: FlagBY,
    short: EnumCountry.by,
    name: "Беларусь",
    code: "+375",
    mask: "+___ (__) ___-__-__",
    placeholder: "+375 (29) 000-00-00",
    selectionStart: 4,
  },
  {
    img: FlagDE,
    short: EnumCountry.de,
    name: "Германия",
    code: "+49",
    mask: "+__ (___) ___-____",
    placeholder: "+374 (999) 000-0000",
    selectionStart: 2,
  },
  {
    img: FlagGE,
    short: EnumCountry.ge,
    name: "Грузия",
    code: "+995",
    mask: "+___ (___) ___-___",
    placeholder: "+995 (999) 000-000",
    selectionStart: 3,
  },
  {
    img: FlagIL,
    short: EnumCountry.il,
    name: "Израиль",
    code: "+972",
    mask: "+___ (__) ___-____",
    placeholder: "+972 (99) 000-0000",
    selectionStart: 3,
  },
  {
    img: FlagIN,
    short: EnumCountry.in,
    name: "Индия",
    code: "+91",
    mask: "+__ (____) ___-____",
    placeholder: "+91 (9999) 000-0000",
    selectionStart: 2,
  },
  {
    img: FlagES,
    short: EnumCountry.es,
    name: "Испания",
    code: "+34",
    mask: "+__ (___) ___-___",
    placeholder: "+34 (999) 000-000",
    selectionStart: 2,
  },
  {
    img: FlagKZ,
    short: EnumCountry.kz,
    name: "Казахстан",
    code: "+7",
    mask: "+_ (___) ___-__-__",
    placeholder: "+7 (999) 000-00-00",
    selectionStart: 2,
  },
  {
    img: FlagCA,
    short: EnumCountry.ca,
    name: "Канада",
    code: "+1",
    mask: "+_ (___) ___-____",
    placeholder: "+1 (999) 000-0000",
    selectionStart: 1,
  },
  {
    img: FlagKG,
    short: EnumCountry.kg,
    name: "Кыргызстан",
    code: "+996",
    mask: "+___ (___) ___-___",
    placeholder: "+996 (999) 000-000",
    selectionStart: 3,
  },
  {
    img: FlagLT,
    short: EnumCountry.lt,
    name: "Литва",
    code: "+370",
    mask: "+___ (__) ___-___",
    placeholder: "+370 (99) 000-000",
    selectionStart: 3,
  },
  {
    img: FlagLV,
    short: EnumCountry.lv,
    name: "Латвия",
    code: "+371",
    mask: "+___ (__) ___-___",
    placeholder: "+371 (99) 000-000",
    selectionStart: 3,
  },
  {
    img: FlagRU,
    short: EnumCountry.ru,
    name: "Россия",
    code: "+7",
    mask: "+_ (___) ___-__-__",
    placeholder: "+7 999 000-00-00",
    selectionStart: 2,
  },
  {
    img: FlagRS,
    short: EnumCountry.rs,
    name: "Сербия",
    code: "+381",
    mask: "+___ (__) ___-____",
    placeholder: "+381 (99) 000-0000",
    selectionStart: 3,
  },
  {
    img: FlagUS,
    short: EnumCountry.us,
    name: "США",
    code: "+1",
    mask: "+_ (___) ___-____",
    placeholder: "+1 (999) 000-0000",
    selectionStart: 1,
  },
  {
    img: FlagTH,
    short: EnumCountry.th,
    name: "Тайланд",
    code: "+66",
    mask: "+__ (__) ___-____",
    placeholder: "+66 (99) 000-0000",
    selectionStart: 2,
  },
  {
    img: FlagTR,
    short: EnumCountry.tr,
    name: "Турция",
    code: "+90",
    mask: "+__ (___) ___-__-__",
    placeholder: "+90 (999) 000-00-00",
    selectionStart: 2,
  },
  {
    img: FlagUZ,
    short: EnumCountry.uz,
    name: "Узбекистан",
    code: "+998",
    mask: "+___ (__) ___-__-__",
    placeholder: "+998 (99) 000-00-00",
    selectionStart: 3,
  },
  {
    img: FlagFR,
    short: EnumCountry.fr,
    name: "Франция",
    code: "+33",
    mask: "+__ (__) __ __ __ __",
    placeholder: "+33 (99) 00 00 00 00",
    selectionStart: 3,
  },
  {
    img: FlagEE,
    short: EnumCountry.ee,
    name: "Эстония",
    code: "+372",
    mask: "+___ (__) ___-___",
    placeholder: "+372 (99) 000-000",
    selectionStart: 3,
  },
]
