import { Inter } from 'next/font/google'

import Providers from './providers'
import 'styles/init.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sheira',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
