export const LinkImagesPreload: string[] = [
    "/icons/fill/apple.svg",
    "/icons/fill/google.svg",
    "/icons/fill/telegram.svg",
    "/icons/fill/trash.svg",
    "/icons/fill/yandex.svg",
    "/icons/fill/vk.svg",
    "/icons/fill/disabled/apple.svg",
    "/icons/fill/disabled/google.svg",
    "/icons/fill/disabled/telegram.svg",
    "/svg/x-close.svg",
    "/svg/eye-off.svg",
    "/svg/eye.svg",
    "/svg/arrow-left.svg",
    "/logo/wordmark.svg",
]
